#ifndef N3D_DOS_WALL_FACTS_H
#define N3D_DOS_WALL_FACTS_H
/* DOS v2.0 independent evidence; see docs/DOS_RUNTIME_FINDINGS_2026-09-22.md.
   Constants describe runtime observations, not packed C struct layouts. */
#define N3D_DOS_MAP_SIDE 64u
#define N3D_DOS_PAIRED_WALL_CAPACITY 64u
#define N3D_DOS_PAIRED_WALL_RECORD_BYTES 18u
#define N3D_DOS_SPECIAL_WALL_CAPACITY 32u
#define N3D_DOS_SPECIAL_WALL_RECORD_BYTES 14u
#define N3D_DOS_OBJECT_REFERENCE_BYTES 6u
#define N3D_DOS_REFERENCED_OBJECT_BYTES 28u
#define N3D_DOS_WALL_STATE_OFFSET 8u
#define N3D_DOS_PAIRED_WALL_STEP 2u
#define N3D_DOS_EXPLOSION_ACTIVE_CLASS 0x2Du
#define N3D_DOS_EXPLOSION_TRIGGER_CLASS_A 0x2Eu
#define N3D_DOS_EXPLOSION_TRIGGER_CLASS_B 0x2Fu
#define N3D_DOS_EXPLOSION_SOUND 0x29u
#define N3D_DOS_WALL_TRANSITION_SOUND_A 0x25u
#define N3D_DOS_WALL_TRANSITION_SOUND_B 0x26u
#endif
